# Generated by Django 4.2.16 on 2024-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DifferentialEq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("func", models.CharField(max_length=100)),
                ("x0", models.FloatField()),
                ("y0", models.FloatField()),
                ("b", models.FloatField()),
                ("h", models.FloatField()),
            ],
        ),
    ]
